name: Trigger Java Review Action

on:
  pull_request:
    paths:
      - '**/*.java'

jobs:
  trigger-review:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Java Review Action
      uses: actions/github-script@v6
      with:
        script: |
          const owner = 'davithss';
          const repo = 'java-review-action';
          const workflow_id = 'review_java.yml';
          const ref = context.payload.pull_request.head.ref;

          await github.actions.createWorkflowDispatch({
            owner,
            repo,
            workflow_id,
            ref
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
