name: Trigger Java Review Action

on:
  pull_request:
    paths:
      - '**/*.java'

jobs:
  trigger-review:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Java Review Action
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: davithss/java-review-action
        event-type: review-java
        client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}"}'
