name: Trigger Java Review Action

on:
  pull_request:
    paths:
      - '**/*.java'

jobs:
  trigger-review:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Java Review Action
      uses: octokit/request-action@v2.4.0
      with:
        route: POST /repos/{owner}/{repo}/dispatches
        owner: davithss
        repo: java-review-action
        event_type: review-java
        client_payload: '{"ref": "${{ github.event.pull_request.head.ref }}"}'
      env:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
